apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ .Release.Name }}-postgresql {{ .Values.database.port }}; do
                echo "Waiting for database..."
                sleep 2
              done
        - name: collect-static
          image: {{ .Values.image.backend }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          env:
            - name: DJANGO_SECRET_KEY
              value: "devsecret"
            - name: DJANGO_DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "*"
          volumeMounts:
            - name: collected-static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media

      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DJANGO_SECRET_KEY
              value: "devsecret"
            - name: DJANGO_DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "*"
          volumeMounts:
            - name: collected-static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media

      volumes:
        - name: collected-static-files
          persistentVolumeClaim:
            claimName: collected-static-pvc
        - name: media-files
          persistentVolumeClaim:
            claimName: media-pvc