apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodgram-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.backend.name }}
            port:
              number: {{ .Values.service.backend.port }}
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.backend.name }}
            port:
              number: {{ .Values.service.backend.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.frontend.name }}
            port:
              number: {{ .Values.service.frontend.port }}